### PR TITLE
Responsive Image Issue

### PR DESCRIPTION
**Pull request by akankshajai**
[BUG] Make Image in Movie's Card Responsive #1
Responsive Image Fixed
Please Review if ok

### CODE REVIEW

**Comment by ikrydev** [comment]
Cool @akankshajai  ..
Before it was merged.. 

please hit star button and follow me ^_^

**Comment by akankshajai** [comment]
Done.

**Comment by ikrydev** [comment]
Star this repo ? @akankshajai

**Comment by ikrydev** [comment]
okay .. thank for contributing to this repo... ^_^

**Pull request merged**
